package davis.c195.controller;

import davis.c195.DAO.CustomerDAO;
import davis.c195.DAO.LocationDAO;
import davis.c195.model.Country;
import davis.c195.model.Customer;
import davis.c195.model.FirstLevelDivision;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

public class AddCustomer implements Initializable {
    @FXML private TextField idField;
    @FXML private TextField nameField;
    @FXML private TextField addressField;
    @FXML private TextField phoneField;
    @FXML private TextField postalCodeField;
    @FXML private ComboBox<String> countryComboBox;
    @FXML private ComboBox<String> divisionComboBox;
    @FXML private Button saveButton;
    @FXML private Button cancelButton;

    /**
     * Initializes the controller class with default values and combo box data.
     *<p>
     * Lambda Expression: Uses forEach to populate the country combo box efficiently.
     * This improves code by providing a cleaner, more functional approach to iterating
     * through countries compared to traditional for loops.
     *</p>
     * @param url The location used to resolve relative paths
     * @param rb The resource bundle for localization
     */
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        try {
            // Disable ID field as it's auto-generated
            idField.setDisable(true);
            idField.setText("Auto-Generated");

            // Load countries into combo box
            LocationDAO.getAllCountries().forEach(country ->
                    countryComboBox.getItems().add(country.getCountry())
            );

            // Set division combo box prompt text
            divisionComboBox.setPromptText("Select a Country First");

        } catch (SQLException e) {
            showAlert("Error", "Error initializing form: " + e.getMessage(), Alert.AlertType.ERROR);
        }
    }

    @FXML
    void onActionCancel(ActionEvent event) {
        if (showConfirmation("Cancel?", "Are you sure you want to cancel? Changes will not be saved.")) {
            closeWindow();
        }
    }

    @FXML
    void onActionSave(ActionEvent event) {
        if (!validateFields()) {
            return;
        }

        try {
            // Get selected division ID
            String selectedDivision = divisionComboBox.getValue();
            int divisionId = -1;

            // Find the division ID that matches the selected division name
            for (FirstLevelDivision division : LocationDAO.getAllDivisions()) {
                if (division.getDivisionName().equals(selectedDivision)) {
                    divisionId = division.getDivisionID();
                    break;
                }
            }

            // Create new customer
            Customer newCustomer = new Customer(
                    0,  // ID will be auto-generated by database
                    nameField.getText(),
                    addressField.getText(),
                    postalCodeField.getText(),
                    phoneField.getText(),
                    divisionId
            );

            // Insert customer
            CustomerDAO.insertCustomer(newCustomer);

            // Show success message and close window
            showAlert("Success", "Customer successfully added!", Alert.AlertType.INFORMATION);
            closeWindow();

        } catch (SQLException e) {
            showAlert("Error", "Error adding customer: " + e.getMessage(), Alert.AlertType.ERROR);
        }
    }

    @FXML
    void onActionCountry(ActionEvent event) {
        try {
            // Clear the division combo box first
            divisionComboBox.getItems().clear();

            // Get selected country
            String selectedCountry = countryComboBox.getValue();

            if (selectedCountry != null) {
                // Find country ID
                int countryId = -1;
                for (Country country : LocationDAO.getAllCountries()) {
                    if (country.getCountry().equals(selectedCountry)) {
                        countryId = country.getCountryID();
                        break;
                    }
                }

                // Get divisions for selected country and populate combo box
                LocationDAO.getDivisionsByCountry(countryId).forEach(division ->
                        divisionComboBox.getItems().add(division.getDivisionName())
                );
            }
        } catch (SQLException e) {
            showAlert("Error", "Error loading divisions: " + e.getMessage(), Alert.AlertType.ERROR);
        }
    }

    private boolean validateFields() {
        StringBuilder errorMessage = new StringBuilder();

        if (nameField.getText().isEmpty()) {
            errorMessage.append("Name is required\n");
        }
        if (addressField.getText().isEmpty()) {
            errorMessage.append("Address is required\n");
        }
        if (postalCodeField.getText().isEmpty()) {
            errorMessage.append("Postal code is required\n");
        }
        if (phoneField.getText().isEmpty()) {
            errorMessage.append("Phone number is required\n");
        }
        if (countryComboBox.getValue() == null) {
            errorMessage.append("Country must be selected\n");
        }
        if (divisionComboBox.getValue() == null) {
            errorMessage.append("Division/State must be selected\n");
        }

        if (errorMessage.length() > 0) {
            showAlert("Validation Error", errorMessage.toString(), Alert.AlertType.ERROR);
            return false;
        }

        return true;
    }

    private void showAlert(String title, String content, Alert.AlertType type) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setContentText(content);
        alert.showAndWait();
    }

    private boolean showConfirmation(String title, String content) {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.setTitle(title);
        alert.setContentText(content);
        return alert.showAndWait().get() == ButtonType.OK;
    }

    private void closeWindow() {
        Stage stage = (Stage) cancelButton.getScene().getWindow();
        stage.close();
    }
}